package net.tigereye.chestcavity.chestcavities.instance;

import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.Container;
import net.minecraft.world.ContainerListener;
import net.minecraft.world.entity.LivingEntity;
import net.tigereye.chestcavity.chestcavities.ChestCavityInventory;
import net.tigereye.chestcavity.chestcavities.IChestCavityType;
import net.tigereye.chestcavity.chestcavities.json.ccInvType.InventoryTypeData;
import net.tigereye.chestcavity.chestcavities.json.ccInvType.InventoryTypeManager;
import net.tigereye.chestcavity.interfaces.ChestCavityEntity;
import net.tigereye.chestcavity.network.ChestCavitySyncService;
import net.tigereye.chestcavity.ui.ChestCavityScreenHandler;
import net.tigereye.chestcavity.service.ChestCavityEvaluationService;
import org.jetbrains.annotations.NotNull;

import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;


public class ChestCavityInstance implements ContainerListener {
    /**
     * Reserved source id for scores generated by the chest-cavity itself.
     * External integrations must use their own modifier id.
     */
    public static final ResourceLocation BASE_ORGAN_SCORE_MODIFIER_ID = new ResourceLocation("chestcavity", "base");

    protected IChestCavityType type;
    public LivingEntity owner;
    public UUID compatibilityId;
    public boolean opened = false;
    public ChestCavityInventory inventory;
    protected Map<ResourceLocation, Float> organScores = new HashMap<>();
    /**
     * Runtime-only additive modifiers. They deliberately do not participate
     * in NBT serialization. The reserved {@link #BASE_ORGAN_SCORE_MODIFIER_ID}
     * stores the latest internal base/inventory evaluation; all other entries
     * are external modifiers.
     */
    private final Map<ResourceLocation, Map<ResourceLocation, Float>> organScoreModifiers = new HashMap<>();
    private int organScoreMutationBatchDepth = 0;
    private boolean organScoreMutationPending = false;
    public int bloodPoisonTimer = 0;
    public int liverTimer = 0;
    public float metabolismRemainder = 0.0F;
    public float lungRemainder = 0.0F;
    public boolean updatePacket = true;
    public ResourceLocation inventoryType;
    private ChestCavitySnapshot lastSnapshot;

    public ChestCavityInstance(IChestCavityType type, LivingEntity owner) {
        this.type = type;
        this.owner = owner;
        this.compatibilityId = owner.getUUID();
        this.inventoryType = type.getInventoryType();
        if (owner instanceof ChestCavityEntity ccEntity) {
            ccEntity.setInventoryTypeData(this.getInventoryType());
        }
        this.inventory = new ChestCavityInventory(this);
        this.commitSnapshot();
    }

    public IChestCavityType getChestCavityType() {
        return this.type;
    }

    /**
     * Returns the currently effective scores, including runtime modifiers.
     *
     * <p>The map remains mutable for backwards compatibility, but direct
     * mutations are transient and may be replaced by the next evaluation.
     * Use {@link #addOrganScoreModifier(ResourceLocation, ResourceLocation,
     * float)} for external values that must survive inventory reconstruction.</p>
     */
    public Map<ResourceLocation, Float> getOrganScores() {
        return this.organScores;
    }

    public float getOrganScore(ResourceLocation id) {
        return this.organScores.getOrDefault(id, 0.0F);
    }

    public float getOrganScoreOrDefault(ResourceLocation id, float defaultValue) {
        return this.organScores.getOrDefault(id, defaultValue);
    }

    /**
     * Replaces the internal score source generated by the evaluator.
     * External modifiers are left untouched.
     */
    public void replaceBaseOrganScores(Map<ResourceLocation, Float> baseScores) {
        this.setBaseOrganScoresInternal(baseScores);
        this.onOrganScoreMutation();
    }

    private void setBaseOrganScoresInternal(Map<ResourceLocation, Float> baseScores) {
        Objects.requireNonNull(baseScores, "baseScores");
        baseScores.forEach((scoreId, amount) ->
                requireModifierArguments(scoreId, BASE_ORGAN_SCORE_MODIFIER_ID, amount)
        );
        if (baseScores.isEmpty()) {
            this.organScoreModifiers.remove(BASE_ORGAN_SCORE_MODIFIER_ID);
        } else {
            this.organScoreModifiers.put(
                    BASE_ORGAN_SCORE_MODIFIER_ID,
                new HashMap<>(baseScores)
            );
        }
        this.rebuildOrganScores();
    }

    /**
     * Adds or replaces an additive modifier identified by {@code modifierId}.
     * Reusing the same identifier updates the existing modifier instead of
     * stacking another copy.
     */
    public void addOrganScoreModifier(ResourceLocation organScoreId, ResourceLocation modifierId, float amount) {
        requireModifierArguments(organScoreId, modifierId, amount);
        requireExternalModifierId(modifierId);
        this.organScoreModifiers
                .computeIfAbsent(modifierId, ignored -> new HashMap<>())
                .put(organScoreId, amount);
        this.rebuildOrganScores();
        this.onOrganScoreMutation();
    }

    public void addOrganScoreModifier(ResourceLocation organScoreId, String modifierId, float amount) {
        this.addOrganScoreModifier(organScoreId, new ResourceLocation(modifierId), amount);
    }

    public void addOrganScoreModifier(String organScoreId, String modifierId, float amount) {
        this.addOrganScoreModifier(new ResourceLocation(organScoreId), modifierId, amount);
    }

    public boolean removeOrganScoreModifier(ResourceLocation organScoreId, ResourceLocation modifierId) {
        Objects.requireNonNull(organScoreId, "organScoreId");
        Objects.requireNonNull(modifierId, "modifierId");
        requireExternalModifierId(modifierId);
        Map<ResourceLocation, Float> scores = this.organScoreModifiers.get(modifierId);
        if (scores == null || scores.remove(organScoreId) == null) {
            return false;
        }
        if (scores.isEmpty()) {
            this.organScoreModifiers.remove(modifierId);
        }
        this.rebuildOrganScores();
        this.onOrganScoreMutation();
        return true;
    }

    public boolean removeOrganScoreModifier(ResourceLocation organScoreId, String modifierId) {
        return this.removeOrganScoreModifier(organScoreId, new ResourceLocation(modifierId));
    }

    public boolean removeOrganScoreModifier(String organScoreId, String modifierId) {
        return this.removeOrganScoreModifier(new ResourceLocation(organScoreId), modifierId);
    }

    public boolean hasOrganScoreModifier(ResourceLocation organScoreId, ResourceLocation modifierId) {
        Objects.requireNonNull(organScoreId, "organScoreId");
        Objects.requireNonNull(modifierId, "modifierId");
        Map<ResourceLocation, Float> scores = this.organScoreModifiers.get(modifierId);
        return scores != null && scores.containsKey(organScoreId);
    }

    public boolean hasOrganScoreModifier(ResourceLocation organScoreId, String modifierId) {
        return this.hasOrganScoreModifier(organScoreId, new ResourceLocation(modifierId));
    }

    public boolean hasOrganScoreModifier(String organScoreId, String modifierId) {
        return this.hasOrganScoreModifier(new ResourceLocation(organScoreId), modifierId);
    }

    public float getOrganScoreModifier(ResourceLocation organScoreId, ResourceLocation modifierId) {
        Objects.requireNonNull(organScoreId, "organScoreId");
        Objects.requireNonNull(modifierId, "modifierId");
        Map<ResourceLocation, Float> scores = this.organScoreModifiers.get(modifierId);
        return scores == null ? 0.0F : scores.getOrDefault(organScoreId, 0.0F);
    }

    public float getOrganScoreModifier(ResourceLocation organScoreId, String modifierId) {
        return this.getOrganScoreModifier(organScoreId, new ResourceLocation(modifierId));
    }

    public float getOrganScoreModifier(String organScoreId, String modifierId) {
        return this.getOrganScoreModifier(new ResourceLocation(organScoreId), modifierId);
    }

    /**
     * Returns an immutable view of modifiers for one score.
     */
    public Map<ResourceLocation, Float> getOrganScoreModifiers(ResourceLocation organScoreId) {
        Objects.requireNonNull(organScoreId, "organScoreId");
        Map<ResourceLocation, Float> external = new HashMap<>();
        this.organScoreModifiers.forEach((modifierId, scores) -> {
            if (!BASE_ORGAN_SCORE_MODIFIER_ID.equals(modifierId)
                    && scores.containsKey(organScoreId)) {
                external.put(modifierId, scores.get(organScoreId));
            }
        });
        return Collections.unmodifiableMap(external);
    }

    public Map<ResourceLocation, Float> getOrganScoreModifiers(String organScoreId) {
        return this.getOrganScoreModifiers(new ResourceLocation(organScoreId));
    }

    /**
     * Returns an immutable source-first copy of all external modifiers.
     */
    public Map<ResourceLocation, Map<ResourceLocation, Float>> getOrganScoreModifiers() {
        Map<ResourceLocation, Map<ResourceLocation, Float>> copy = new HashMap<>();
        this.organScoreModifiers.forEach((modifierId, scores) -> {
            if (!BASE_ORGAN_SCORE_MODIFIER_ID.equals(modifierId)) {
                copy.put(modifierId, Collections.unmodifiableMap(new HashMap<>(scores)));
            }
        });
        return Collections.unmodifiableMap(copy);
    }

    /**
     * Returns an immutable source-first copy of all sources, including the
     * reserved base source.
     */
    public Map<ResourceLocation, Map<ResourceLocation, Float>> getAllOrganScoreModifiers() {
        Map<ResourceLocation, Map<ResourceLocation, Float>> copy = new HashMap<>();
        this.organScoreModifiers.forEach((modifierId, scores) ->
                copy.put(modifierId, Collections.unmodifiableMap(new HashMap<>(scores))));
        return Collections.unmodifiableMap(copy);
    }

    public void clearOrganScoreModifiers() {
        boolean changed = this.organScoreModifiers.keySet()
                .removeIf(id -> !BASE_ORGAN_SCORE_MODIFIER_ID.equals(id));
        if (!changed) {
            return;
        }
        this.rebuildOrganScores();
        this.onOrganScoreMutation();
    }

    public void clearOrganScoreModifiers(ResourceLocation organScoreId) {
        Objects.requireNonNull(organScoreId, "organScoreId");
        boolean changed = false;
        Iterator<Map.Entry<ResourceLocation, Map<ResourceLocation, Float>>> iterator =
                this.organScoreModifiers.entrySet().iterator();
        while (iterator.hasNext()) {
            Map.Entry<ResourceLocation, Map<ResourceLocation, Float>> entry = iterator.next();
            if (!BASE_ORGAN_SCORE_MODIFIER_ID.equals(entry.getKey())
                    && entry.getValue().remove(organScoreId) != null) {
                changed = true;
            }
            if (entry.getValue().isEmpty()) {
                iterator.remove();
            }
        }
        if (!changed) {
            return;
        }
        this.rebuildOrganScores();
        this.onOrganScoreMutation();
    }

    public void clearOrganScoreModifiers(String organScoreId) {
        this.clearOrganScoreModifiers(new ResourceLocation(organScoreId));
    }

    private void rebuildOrganScores() {
        this.organScores.clear();
        this.organScoreModifiers.values().forEach(scores -> {
            scores.forEach((scoreId, amount) -> {
                this.organScores.merge(scoreId, amount, Float::sum);
            });
        });
    }

    private void onOrganScoreMutation() {
        this.markDirty();
        this.organScoreMutationPending = true;
        if (this.organScoreMutationBatchDepth > 0) {
            return;
        }
        this.flushOrganScoreMutation();
    }

    /**
     * Defers effect and sync application until the matching
     * {@link #endOrganScoreMutationBatch()} call. Used by the evaluator so
     * base-score replacement and integration changes are applied atomically.
     */
    public void beginOrganScoreMutationBatch() {
        this.organScoreMutationBatchDepth++;
    }

    public void endOrganScoreMutationBatch() {
        if (this.organScoreMutationBatchDepth <= 0) {
            throw new IllegalStateException("No organ-score mutation batch is active");
        }
        this.organScoreMutationBatchDepth--;
        if (this.organScoreMutationBatchDepth == 0) {
            this.flushOrganScoreMutation();
        }
    }

    private void flushOrganScoreMutation() {
        if (!this.organScoreMutationPending) {
            return;
        }
        this.organScoreMutationPending = false;
        ChestCavityEvaluationService.updateEffectsAndSync(this);
    }

    private static void requireModifierArguments(ResourceLocation organScoreId, ResourceLocation modifierId, float amount) {
        Objects.requireNonNull(organScoreId, "organScoreId");
        Objects.requireNonNull(modifierId, "modifierId");
        if (!Float.isFinite(amount)) {
            throw new IllegalArgumentException("Organ score modifier amount must be finite");
        }
    }

    private static void requireExternalModifierId(ResourceLocation modifierId) {
        if (BASE_ORGAN_SCORE_MODIFIER_ID.equals(modifierId)) {
            throw new IllegalArgumentException(
                    "The reserved base organ-score modifier can only be changed by replaceBaseOrganScores"
            );
        }
    }

    public float getOldOrganScore(ResourceLocation id) {
        return this.lastSnapshot == null ? 0.0F : this.lastSnapshot.getOrganScore(id);
    }

    public ResourceLocation getInventoryType() {
        return this.inventoryType;
    }

    public InventoryTypeData getInventoryTypeData() {
        return InventoryTypeManager.getInventoryTypeData(this.inventoryType);
    }

    public ChestCavitySnapshot createSnapshot() {
        return ChestCavitySnapshot.capture(this);
    }

    public boolean hasInventoryChangesSinceSnapshot() {
        return this.lastSnapshot == null || this.lastSnapshot.hasInventoryChanges(this);
    }

    public boolean hasOrganScoreChangesSinceSnapshot() {
        return this.lastSnapshot == null || this.lastSnapshot.hasOrganScoreChanges(this);
    }

    public void markDirty() {
        this.updatePacket = true;
        ChestCavitySyncService.enqueue(this);
    }

    public void setOpened(boolean opened) {
        if (this.opened != opened) {
            this.opened = opened;
            this.markDirty();
        }
    }

    public void applyRemoteState(boolean opened, Map<ResourceLocation, Float> organScores) {
        this.opened = opened;
        this.organScoreModifiers.clear();
        this.setBaseOrganScoresInternal(organScores);
        this.organScoreMutationPending = false;
        this.commitSnapshot();
    }

    public void markSyncPending() {
        this.updatePacket = true;
    }

    public void acknowledgeSync() {
        this.updatePacket = false;
    }

    /**
     * Commits the current state as the previous-state baseline used by
     * change detection.
     */
    public void commitSnapshot() {
        if (this.inventory == null) {
            return;
        }
        this.lastSnapshot = ChestCavitySnapshot.capture(this);
    }

    @Override
    public void containerChanged(@NotNull Container sender) {
        if (!this.hasInventoryChangesSinceSnapshot()) return;
        this.markDirty();
        ChestCavityEvaluationService.evaluate(this);
        this.syncInventoryTypeData();
    }

    public void setInventoryType(ResourceLocation inventoryType) {
        int newInventorySize = InventoryTypeManager.getInventoryTypeData(inventoryType).getSlotSize();
        ChestCavityInventory newInventory = new ChestCavityInventory(newInventorySize);
        for (int i = 0; i < this.inventory.getContainerSize(); i++) {
            if (newInventorySize <= i) {
                this.owner.spawnAtLocation(this.inventory.getItem(i));
                continue;
            }
            newInventory.setItem(i, this.inventory.getItem(i));
        }
        this.replaceInventory(newInventory, inventoryType);
    }

    public void replaceInventory(ChestCavityInventory replacement, ResourceLocation newInventoryType) {
        this.replaceInventory(replacement, newInventoryType, true);
    }

    public void replaceInventory(ChestCavityInventory replacement, ResourceLocation newInventoryType, boolean evaluate) {
        if (replacement == null) {
            throw new IllegalArgumentException("replacement inventory cannot be null");
        }
        if (this.inventory != null) {
            this.inventory.removeListener(this);
        }
        this.inventoryType = newInventoryType;
        replacement.setInstance(this);
        this.inventory = replacement;
        this.inventory.addListener(this);
        this.syncInventoryTypeData();
        if (this.owner instanceof ServerPlayer player && player.containerMenu instanceof ChestCavityScreenHandler) {
            player.closeContainer();
        }
        this.markDirty();
        if (evaluate) {
            this.containerChanged(this.inventory);
        }
    }

    private void syncInventoryTypeData() {
        if (this.owner instanceof ChestCavityEntity ccEntity) {
            ccEntity.setInventoryTypeData(this.inventoryType);
        }
    }

    public void fromTag(CompoundTag tag, LivingEntity owner) {
        this.owner = owner;
        // Modifiers are runtime-only and must not survive an NBT reload.
        this.organScoreModifiers.clear();
        this.organScoreMutationPending = false;
        CompoundTag ccTag;
        if (tag.contains("ChestCavity")) {
            ccTag = tag.getCompound("ChestCavity");
            this.opened = ccTag.getBoolean("opened");
            this.bloodPoisonTimer = ccTag.getInt("KidneyTimer");
            this.liverTimer = ccTag.getInt("LiverTimer");
            this.metabolismRemainder = ccTag.getFloat("MetabolismRemainder");
            this.lungRemainder = ccTag.getFloat("LungRemainder");
            ResourceLocation loadedInventoryType = new ResourceLocation(ccTag.getString("InventoryType"));
            if (ccTag.contains("CompatibilityId")) {
                this.compatibilityId = ccTag.getUUID("CompatibilityId");
            } else {
                this.compatibilityId = owner.getUUID();
            }

            int newInventorySize = InventoryTypeManager.getInventoryTypeData(loadedInventoryType).getSlotSize();
            if (newInventorySize < this.inventory.getContainerSize()) {
                for (int i = newInventorySize; i < this.inventory.getContainerSize(); i++) {
                    this.owner.spawnAtLocation(this.inventory.getItem(i));
                }
            }

            ChestCavityInventory loadedInventory = new ChestCavityInventory(newInventorySize);
            if (ccTag.contains("Inventory")) {
                ListTag nbtList = ccTag.getList("Inventory", 10);
                loadedInventory.fromTag(nbtList);
            }
            this.replaceInventory(loadedInventory, loadedInventoryType, false);
            ChestCavityEvaluationService.evaluate(this);
        }
    }

    public void toTag(CompoundTag tag, LivingEntity owner) {
        CompoundTag ccTag = new CompoundTag();
        ccTag.putBoolean("opened", this.opened);
        ccTag.putString("InventoryType", this.inventoryType.toString());
        ccTag.putUUID("CompatibilityId", this.compatibilityId);
        ccTag.putInt("KidneyTimer", this.bloodPoisonTimer);
        ccTag.putInt("LiverTimer", this.liverTimer);
        ccTag.putFloat("MetabolismRemainder", this.metabolismRemainder);
        ccTag.putFloat("LungRemainder", this.lungRemainder);
        ccTag.put("Inventory", this.inventory.createTag());
        tag.put("ChestCavity", ccTag);
    }

    public void copyFrom(ChestCavityInstance other) {
        this.opened = other.opened;
        this.type = other.type;
        this.compatibilityId = other.compatibilityId;
        this.liverTimer = other.liverTimer;
        this.bloodPoisonTimer = other.bloodPoisonTimer;
        this.metabolismRemainder = other.metabolismRemainder;
        this.lungRemainder = other.lungRemainder;
        this.organScoreModifiers.clear();
        other.organScoreModifiers.forEach((scoreId, modifiers) ->
                this.organScoreModifiers.put(scoreId, new HashMap<>(modifiers)));
        this.replaceInventory(other.inventory.copyFor(this), other.inventoryType, false);
        ChestCavityEvaluationService.evaluate(this);
    }

}
