package net.tigereye.chestcavity.registration;

import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.tigereye.chestcavity.ChestCavity;

public class CCFoodComponents {
    public static final FoodProperties ANIMAL_MUSCLE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.4F).meat().fast().build();
    public static final FoodProperties SMALL_ANIMAL_MUSCLE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.2F).meat().fast().build();
    public static final FoodProperties BURNT_MEAT_CHUNK_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.8F).meat().fast().build();
    public static final FoodProperties RAW_BUTCHERED_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.4F).meat().build();
    public static final FoodProperties COOKED_BUTCHERED_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.8F).meat().build();
    public static final FoodProperties RAW_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.6F).meat().fast().build();
    public static final FoodProperties COOKED_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(1.2F).meat().fast().build();
    public static final FoodProperties RAW_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.4F).meat().build();
    public static final FoodProperties COOKED_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(0.8F).meat().build();
    public static final FoodProperties RAW_RICH_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.6F).meat().build();
    public static final FoodProperties COOKED_RICH_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(1.2F).meat().build();
    public static final FoodProperties RAW_MINI_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.4F).meat().build();
    public static final FoodProperties COOKED_MINI_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(6).saturationMod(0.8F).meat().build();
    public static final FoodProperties RAW_RICH_MINI_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.6F).meat().build();
    public static final FoodProperties COOKED_RICH_MINI_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(6).saturationMod(1.2F).meat().build();
    public static final FoodProperties ROTTEN_MUSCLE_FOOD_COMPONENT;
    public static final FoodProperties ROTTEN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties INSECT_MUSCLE_FOOD_COMPONENT;
    public static final FoodProperties RAW_TOXIC_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_TOXIC_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_TOXIC_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_TOXIC_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_TOXIC_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_TOXIC_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties RAW_RICH_TOXIC_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_RICH_TOXIC_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties ALIEN_MUSCLE_FOOD_COMPONENT;
    public static final FoodProperties RAW_ALIEN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_ALIEN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_ALIEN_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_ALIEN_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_ALIEN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_ALIEN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties RAW_RICH_ALIEN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_RICH_ALIEN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties DRAGON_MUSCLE_FOOD_COMPONENT;
    public static final FoodProperties RAW_DRAGON_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_DRAGON_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_DRAGON_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_DRAGON_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_DRAGON_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_DRAGON_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties RAW_RICH_DRAGON_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_RICH_DRAGON_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties DRAGON_HEART_FOOD_COMPONENT;
    public static final FoodProperties HUMAN_MUSCLE_FOOD_COMPONENT;
    public static final FoodProperties RAW_MAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_MAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_HUMAN_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties COOKED_HUMAN_ORGAN_MEAT_FOOD_COMPONENT;
    public static final FoodProperties RAW_HUMAN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_HUMAN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties RAW_RICH_HUMAN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties COOKED_RICH_HUMAN_SAUSAGE_FOOD_COMPONENT;
    public static final FoodProperties CUD_FOOD_COMPONENT;

    public CCFoodComponents() {
    }

    static {
        ROTTEN_MUSCLE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.1F).effect(new MobEffectInstance(MobEffects.HUNGER, 600, 0), 0.8F).meat().build();
        ROTTEN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(0.1F).effect(new MobEffectInstance(MobEffects.HUNGER, 600, 0), 0.8F).meat().build();
        INSECT_MUSCLE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.4F).meat().fast().effect(new MobEffectInstance(MobEffects.POISON, 80), 1.0F).build();
        RAW_TOXIC_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.POISON, 80), 1.0F).build();
        COOKED_TOXIC_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.CONFUSION, 160, 1), 1.0F).build();
        RAW_TOXIC_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.6F).meat().fast().effect(new MobEffectInstance(MobEffects.POISON, 80), 1.0F).build();
        COOKED_TOXIC_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(1.2F).meat().fast().effect(new MobEffectInstance(MobEffects.CONFUSION, 160, 1), 1.0F).build();
        RAW_TOXIC_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.POISON, 80), 1.0F).build();
        COOKED_TOXIC_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.CONFUSION, 160, 1), 1.0F).build();
        RAW_RICH_TOXIC_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.6F).meat().effect(new MobEffectInstance(MobEffects.POISON, 80), 1.0F).build();
        COOKED_RICH_TOXIC_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(1.2F).meat().effect(new MobEffectInstance(MobEffects.CONFUSION, 160, 1), 1.0F).build();
        ALIEN_MUSCLE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.4F).meat().fast().effect(new MobEffectInstance(MobEffects.LEVITATION, 20), 1.0F).build();
        RAW_ALIEN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.LEVITATION, 80), 1.0F).build();
        COOKED_ALIEN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.SLOW_FALLING, 10, 1), 1.0F).build();
        RAW_ALIEN_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.6F).meat().fast().effect(new MobEffectInstance(MobEffects.LEVITATION, 40), 1.0F).build();
        COOKED_ALIEN_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(1.2F).meat().fast().effect(new MobEffectInstance(MobEffects.SLOW_FALLING, 15, 1), 1.0F).build();
        RAW_ALIEN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.LEVITATION, 80), 1.0F).build();
        COOKED_ALIEN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.SLOW_FALLING, 20, 1), 1.0F).build();
        RAW_RICH_ALIEN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.6F).meat().effect(new MobEffectInstance(MobEffects.LEVITATION, 320), 1.0F).build();
        COOKED_RICH_ALIEN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(1.2F).meat().effect(new MobEffectInstance(MobEffects.SLOW_FALLING, 40, 1), 1.0F).build();
        DRAGON_MUSCLE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.4F).meat().fast().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 300), 1.0F).alwaysEat().build();
        RAW_DRAGON_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 900), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 900), 1.0F).alwaysEat().build();
        COOKED_DRAGON_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 150, 1), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 150, 1), 1.0F).alwaysEat().build();
        RAW_DRAGON_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.6F).meat().fast().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 1800), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 1800), 1.0F).alwaysEat().build();
        COOKED_DRAGON_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(1.2F).meat().fast().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300, 1), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 300, 1), 1.0F).alwaysEat().build();
        RAW_DRAGON_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 9600), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 9600), 1.0F).alwaysEat().build();
        COOKED_DRAGON_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 1800, 1), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 1800, 1), 1.0F).alwaysEat().build();
        RAW_RICH_DRAGON_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.6F).meat().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 19200), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 19200), 1.0F).alwaysEat().build();
        COOKED_RICH_DRAGON_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(8).saturationMod(1.2F).meat().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 3600, 1), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 3600, 1), 1.0F).alwaysEat().build();
        DRAGON_HEART_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.4F).meat().fast().effect(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 600, 3), 1.0F).effect(new MobEffectInstance(MobEffects.DIG_SPEED, 600, 3), 1.0F).effect(new MobEffectInstance(MobEffects.POISON, 2, 3), 1.0F).effect(new MobEffectInstance(MobEffects.WITHER, 2, 3), 1.0F).effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 2, 3), 1.0F).effect(new MobEffectInstance(MobEffects.HUNGER, 2, 3), 1.0F).effect(new MobEffectInstance(MobEffects.CONFUSION, 2, 3), 1.0F).effect(new MobEffectInstance(MobEffects.BLINDNESS, 2, 3), 1.0F).effect(new MobEffectInstance(MobEffects.SLOW_FALLING, 2, 3), 1.0F).effect(new MobEffectInstance(MobEffects.LEVITATION, 2, 3), 1.0F).alwaysEat().build();
        HUMAN_MUSCLE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(2).saturationMod(0.4F).meat().fast().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).build();
        RAW_MAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).build();
        COOKED_MAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).build();
        RAW_HUMAN_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(3).saturationMod(0.6F).meat().fast().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).build();
        COOKED_HUMAN_ORGAN_MEAT_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(4).saturationMod(1.2F).meat().fast().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).build();
        RAW_HUMAN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(5).saturationMod(0.4F).meat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).build();
        COOKED_HUMAN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(9).saturationMod(0.8F).meat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).build();
        RAW_RICH_HUMAN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(5).saturationMod(0.6F).meat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 1), ChestCavity.config.RISK_OF_PRIONS).build();
        COOKED_RICH_HUMAN_SAUSAGE_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(9).saturationMod(1.2F).meat().effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.DIG_SLOWDOWN, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).effect(new MobEffectInstance(MobEffects.WEAKNESS, 24000, 0), ChestCavity.config.RISK_OF_PRIONS).build();
        CUD_FOOD_COMPONENT = (new FoodProperties.Builder()).nutrition(1).saturationMod(0.1F).build();
    }
}